# GitHub Actions Workflow for deploying to Alibaba Cloud Function Compute
name: Deploy to Alibaba Cloud FC

# This workflow runs on every push to the 'main' branch
on:
    push:
        branches:
            - main

jobs:
    deploy-function:
        runs-on: ubuntu-latest # Use the latest available runner

        steps:
            # 1. Checks out your repository code
            - name: Checkout Code
              uses: actions/checkout@v4

            # Adding as step in .env file
            - name: Create .env file
              run: |
                  echo "ALIYUN_ACCESS_KEY_ID=${{ secrets.ALIYUN_ACCESS_KEY_ID }}" >> .env
                  echo "ALIYUN_ACCESS_KEY_SECRET=${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}" >> .env
                  echo "MNS_ACCOUNT_ID=${{ secrets.MNS_ACCOUNT_ID }}" >> .env
                  echo "MNS_QUEUE_NAME=${{ secrets.MNS_QUEUE_NAME }}" >> .env
                  echo "FCM_CREDENTIALS_JSON='${{ secrets.FCM_CREDENTIALS_JSON }}'" >> .env
                  echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
                  echo "MONGO_DBNAME=${{ secrets.MONGO_DBNAME }}" >> .env

            - name: Verify the env file has values
              run: cat .env

            # 2. Sets up Node.js environment
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18" # Must match the runtime in your s.yaml

            # 3. Install Serverless Devs CLI
            - name: Install Serverless Devs
              run: npm install @serverless-devs/s -g

            # 4. Configure Serverless Devs with credentials from GitHub Secrets
            - name: Configure Credentials
              run: s config add --AccessKeyID ${{ secrets.ALIYUN_ACCESS_KEY_ID }} --AccessKeySecret ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }} -a default -f

            - name: Get Aliyun Authorization Token
              id: get_token
              run: |
                  echo "ACCESS_KEY_ID=${{ secrets.ALIYUN_ACCESS_KEY_ID }}"
                  echo "ACCESS_KEY_SECRET=${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}"
                  echo "ALI_BABA_REGION=${{ secrets.ALIYUN_REGION }}"
                  echo "CR_INSTANCE_ID=${{ secrets.ALIYUN_CR_INSTANCE_ID }}"

            # 5. Deploy the function
            - name: Deploy Function
              # We pass the secrets as environment variables so s.yaml can access them
              run: s deploy --use-local -y
